name: optool-inject-from-url

on:
  workflow_dispatch:
    inputs:
      ipa_url:
        description: 'Google Drive / direct URL to crssplay_frida_localpatched.ipa'
        required: true
      dylib_url:
        description: 'Google Drive / direct URL to frida-gadget-17.3.2-ios-universal.dylib'
        required: true

jobs:
  optoolize:
    runs-on: macos-latest
    steps:
      - name: Checkout (empty repo)
        uses: actions/checkout@v4

      - name: Install Python & gdown
        run: |
          brew install python || true
          python3 -m pip install --upgrade pip gdown

      - name: Download optool binary
        run: |
          curl -L https://github.com/alexzielenski/optool/releases/download/0.1/optool.zip -o optool.zip
          unzip optool.zip
          chmod +x optool
          sudo mv optool /usr/local/bin/optool
          optool --version || true

      - name: Prepare workdir
        run: mkdir workdir

      - name: Download IPA and dylib
        run: |
          cd workdir
          gdown "${{ github.event.inputs.ipa_url }}" -O crssplay_frida_localpatched.ipa
          gdown "${{ github.event.inputs.dylib_url }}" -O frida-gadget-17.3.2-ios-universal.dylib
          ls -lh

      - name: Unzip IPA
        run: |
          cd workdir
          unzip -o crssplay_frida_localpatched.ipa -d work_unzip

      - name: Copy dylib into Frameworks
        run: |
          cd workdir/work_unzip/Payload
          APP=$(ls -1 | grep '\.app' | head -n1)
          echo "App folder: $APP"
          mkdir -p "$APP/Frameworks"
          cp ../frida-gadget-17.3.2-ios-universal.dylib "$APP/Frameworks/"
          ls -lh "$APP/Frameworks"

      - name: Inject LC_LOAD_DYLIB into dfxm
        run: |
          cd workdir/work_unzip
          APP=$(ls Payload | grep '\.app' | head -n1)
          EXEC=Payload/"$APP"/dfxm
          echo "Target executable: $EXEC"
          /usr/local/bin/optool install -c load -p @executable_path/Frameworks/frida-gadget-17.3.2-ios-universal.dylib -t "$EXEC"

      - name: Repack IPA
        run: |
          cd workdir/work_unzip
          zip -r -y ../crssplay_frida_optooled.ipa Payload

      - name: Upload patched IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: crssplay_frida_optooled
          path: workdir/crssplay_frida_optooled.ipa
